# Site settings
title: "Godslove's Geospatial Data Science Portfolio"
description: "Urban analytics • Environmental modeling • Survey perception analysis"
baseurl: "" # Leave empty for user/organization site
url: "https://gekahortor.github.io"

# Author info
author:
  name: "Godslove"
  email: "your.email@example.com"
  linkedin: "https://linkedin.com/in/yourprofile"
  github: "https://github.com/gekahortor"

# Theme
theme: jekyll-theme-cayman

# Markdown & formatting
markdown: kramdown
kramdown:
  input: GFM

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
